In [2]:
import numpy as np

arr= np.array([5,10,15,20])
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)

[ 5 10 15 20]
1
4
int64
(4,)


In [4]:
arr= np.ones((3,3), dtype=np.int32)
print(arr)
print(arr.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32


In [5]:
z=np.arange(1,51, 5)
print(z)

[ 1  6 11 16 21 26 31 36 41 46]


In [10]:
z=np.linspace(0,100, 6)
print(z)

[  0.  20.  40.  60.  80. 100.]


In [11]:
z= np.full((2,3), 7)
print(z)

[[7 7 7]
 [7 7 7]]


In [20]:
z=np.arange(1,25)
b=z.reshape(6,4)
c=b.reshape(2,12)

print(c)
print(b)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [27]:
z=np.arange(1,25)
e=z.ravel()
d=z.flatten()
e[0]=1
d[0]=900
print(e)
print(d)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[900   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [36]:
a = np.arange(1, 17).reshape(4, 4)
b=a[3:]
print(b)
print(a)

[[13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [35]:
a = np.arange(1, 17).reshape(4, 4)
b=a[0:2, 0:2]
print(b)

[[1 2]
 [5 6]]


In [41]:
a = np.arange(1, 17).reshape(4, 4)
b=a[1:3,1:3]
print(b)

[[ 6  7]
 [10 11]]


In [42]:
a = np.arange(1, 17).reshape(4, 4)
b=a[a%2==0]
print(b)

[ 2  4  6  8 10 12 14 16]


In [44]:
a = np.arange(1, 17).reshape(4, 4)
b=a[[1,3],[2,0]]
print(b)

[ 7 13]


In [47]:
a=np.array([5,10,15,20])
print(a+5)


[10 15 20 25]


In [49]:
a=np.arange(1,10).reshape(3,3)
print(a*0.5)

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [50]:
m=np.arange(1,10).reshape(3,3)
v=np.array([10,20,30])
print(m*v)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [52]:
m=np.arange(1,10).reshape(3,3)
col=np.array([[2],[3],[4]])
print(m*col)

[[ 2  4  6]
 [12 15 18]
 [28 32 36]]


In [53]:
m =np.array([[10, 20, 30, 40],[50, 60, 70, 80]])

v = np.array([1, 2, 3, 4])
print(m+v)

[[11 22 33 44]
 [51 62 73 84]]


In [62]:
x = np.arange(2, 50, 2).reshape(6, 4)
print(x.sum())

print(x.sum(axis=0))
print(x.mean(axis=1))
print(x.argmax())
print(x.max())
print(x.min(axis=0))

600
[132 144 156 168]
[ 5. 13. 21. 29. 37. 45.]
23
48
[2 4 6 8]


In [68]:
a = np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate([a,b], axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [70]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate([a,b], axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [73]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.hstack([a,b])
d=np.vstack([a,b])
print(c)
print(d)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [75]:
x = np.arange(1, 13).reshape(3, 4)
b=np.split(x,3)
print(b)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [77]:
x = np.arange(1, 13).reshape(3, 4)
b=np.hsplit(x,2)
print(b)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [84]:
x = np.arange(1, 7).reshape(2, 3)
b=np.hsplit(x,3)
print(b)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [5]:
import numpy as np

x = np.random.rand(3, 3)
y=np.random.randint(1, 100, size=(3,4))

z=np.random.random(10)      # 1D
a=np.random.random((2,3)) 
b=np.random.randn(3, 3)

print(x)
print(y)
print(z)
print(a)
print(b)

[[0.23130169 0.1082562  0.40084317]
 [0.40895133 0.37907805 0.39856546]
 [0.33436684 0.50421262 0.90706207]]
[[68 30 89 74]
 [23 44 63 32]
 [10 81 44 65]]
[0.71832576 0.6962619  0.98598192 0.77985572 0.59712872 0.72400081
 0.20867519 0.23207316 0.04043421 0.4776681 ]
[[8.36696288e-01 4.31398448e-01 9.36665479e-01]
 [4.91479315e-04 6.18225062e-01 2.13155954e-01]]
[[ 0.43287105  0.69008478 -1.47515619]
 [-1.61486144 -0.51271321 -1.92450229]
 [-0.47430465  1.49733865 -1.39528135]]


In [9]:
arr = np.array([10, 20, 30, 40, 50])
np.random.choice(arr, size=3)

array([40, 30, 20])

In [12]:
x = np.arange(1, 11)
y=np.random.permutation(x)
print(y)

[ 4  7  1  9 10  3  2  6  8  5]


In [15]:
np.random.seed(10)
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]


In [16]:
import numpy as np
a = np.array([5, 12, 7, 20, 3, 18])
mask = a > 10
print(mask)


[False  True False  True False  True]


In [17]:
arr = np.array([4, 15, 7, 22, 9, 30, 11, 3])
mask=arr>10
print(mask)

[False  True False  True False  True  True False]


In [18]:
arr = np.array([4, 15, 7, 22, 9, 30, 11, 3])
z=arr[arr%2==0]
print(z)

[ 4 22 30]


In [20]:
arr = np.array([4, 15, 7, 22, 9, 30, 11, 3])
z=arr[(arr>10) & (arr<25)]
print(z)

[15 22 11]


In [23]:
arr = np.array([4, 15, 7, 22, 9, 30, 11, 3])
z=arr[(arr%2 !=0) & (arr !=15)]
print(z)

[ 7  9 11  3]


In [31]:
arr = np.array([4, 15, 7, 22, 9, 30, 11, 3])
arr[arr<10] = 0
print(arr)

[ 0 15  0 22  0 30 11  0]


In [32]:
arr = np.array([4, 15, 7, 22, 9, 30, 11, 3])
new = np.where(arr < 10, 0, arr)
print(new)

[ 0 15  0 22  0 30 11  0]


In [34]:
arr = np.array([10, np.nan, 25, np.nan, 40, 55])
z= np.isnan(arr).sum()
print(z)

2


In [36]:
arr = np.array([10, np.nan, 25, np.nan, 40, 55])
z= arr[~np.isnan(arr)]
print(z)

[10. 25. 40. 55.]


In [40]:
arr = np.array([10, np.nan, 25, np.nan, 40, 55])
arr[np.isnan(arr)]=0
print(arr)

[10.  0. 25.  0. 40. 55.]


In [41]:
arr = np.array([10, np.nan, 25, np.nan, 40, 55])
arr[np.isnan(arr)]= np.nanmean(arr)
print(arr)

[10.  32.5 25.  32.5 40.  55. ]


In [48]:
import numpy as np

m=np.array([[1, np.nan, 3],
   [np.nan, 5, 6]])
mean_val = np.nanmean(m)
m[np.isnan(m)] = mean_val
print(m)

[[1.   3.75 3.  ]
 [3.75 5.   6.  ]]
