##  Import & First Array

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [2]:
a= np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [6]:
arr=np.array([10,20,30,40])
print(arr.shape)
print(arr.dtype)

(4,)
int64


## Array creation helpers

In [8]:
np.zeros((2,3))      # zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(4)           # ones


array([1., 1., 1., 1.])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Array shapes & reshaping

In [26]:
a = np.arange(12)
b = a.reshape(3,4)
print(a)
print(b)
print(a.shape, b.shape)
# flatten
c = b.ravel()
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(12,) (3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
a= np.arange(24)
print(a)
b=a.reshape(4,6)
print(b)


d=b.reshape(2,12)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [3]:
import pandas as pd

s = pd.Series([10, 20, 30], index=["A", "B", "C"])
print(s)

A    10
B    20
C    30
dtype: int64


In [4]:
import pandas as pd
sales = pd.Series([2000, 3500, 1800, 5000], index=["Mon", "Tue", "Wed", "Thu"])
print("Original Series:\n", sales)

print("Sales > 3000:\n", sales[sales > 3000])

print("Sum =", sales.sum())
print("Sorted:\n", sales.sort_values())


Original Series:
 Mon    2000
Tue    3500
Wed    1800
Thu    5000
dtype: int64
Sales > 3000:
 Tue    3500
Thu    5000
dtype: int64
Sum = 12300
Sorted:
 Wed    1800
Mon    2000
Tue    3500
Thu    5000
dtype: int64


In [14]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

[10 20 30 40 50]
(5,)
5
int64
1


In [23]:
import numpy as np
z=np.zeros((3,4), dtype=np.int32)
print(z)
print(z.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [37]:
import numpy as np
import pandas as pd
z=np.ones((5,5))
o=z.astype(float)
print(o)
print("ndim:", o.ndim)
print("shape:", o.shape)
print("size:", o.size)
print("dtype:", o.dtype)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
ndim: 2
shape: (5, 5)
size: 25
dtype: float64


In [56]:
z= np.random.default_rng(2)
r = z.integers(1, 51, size=5)
print(r)

[42 14  6 15 21]


In [60]:
rng = np.random.default_rng(0)
n = rng.uniform(0, 10, size=(3,3))
print(n)

[[6.36961687 2.69786714 0.40973524]
 [0.16527636 8.13270239 9.12755577]
 [6.06635776 7.29496561 5.43624991]]


In [63]:
z= np.random.random(15)
r= z.reshape(3,5)
print(r)


[[0.52694356 0.53404662 0.03609014 0.27795037 0.4312836 ]
 [0.40243315 0.56334823 0.21368934 0.02539121 0.88210668]
 [0.43182916 0.79930309 0.86104377 0.50102145 0.94401103]]


In [66]:
z=np.arange(10,21)
print(z)

print("First theree:", z[:3])
print("Last three:", z[-3:])
print("Alternamte:", z[::2])

[10 11 12 13 14 15 16 17 18 19 20]
First theree: [10 11 12]
Last three: [18 19 20]
Alternamte: [10 12 14 16 18 20]


In [69]:
z=np.arange(1,17).reshape(4,4)
print(z)

mid= z[1:3, 1:3]
print(mid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]


In [70]:
b= np.array([10,20,30,40,50,])
print(b+2)

[12 22 32 42 52]
